language: node_js
node_js:
  - "node"

addons:
  apt:
    packages:
    - libgconf-2-4

before_install:
  - npm install
  - npm run build
  - npm run start
  - npm run mountebank.start

script:
  - npm run unit.test.coverage
  - npm run ui.test
