language: node_js
node_js:
  - "node"

addons:
  apt:
    packages:
    - libgconf-2-4

install:
  - npm install
  - npm run build
  - npm run start.ci
  - npm run mountebank.start.ci

script:
  - npm run unit.test.coverage
  - npm run ui.test
